# Generated by Django 3.2.10 on 2023-08-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cuisinedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='fooditems')),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='recipedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=20, null=True)),
                ('recipe_name', models.CharField(blank=True, max_length=50, null=True)),
                ('about', models.CharField(blank=True, max_length=500, null=True)),
                ('recipe_image', models.ImageField(blank=True, null=True, upload_to='recipes')),
                ('ingredients', models.CharField(blank=True, max_length=500, null=True)),
                ('recipe_desc', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
