# Generated by Django 3.2.10 on 2023-08-12 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerdb',
            name='profile',
        ),
    ]
