# Generated by Django 3.2.10 on 2023-08-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_remove_registerdb_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='favdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='favorites')),
                ('recipe', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
