# Generated by Django 3.2.10 on 2023-08-13 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_favdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favdb',
            name='image',
        ),
    ]
