# Generated by Django 3.2.10 on 2023-08-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_remove_favdb_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='downloaddb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(blank=True, max_length=50, null=True)),
                ('ringredients', models.CharField(blank=True, max_length=500, null=True)),
                ('rdesc', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
