# Generated by Django 3.2.10 on 2023-08-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_downloaddb'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloaddb',
            name='rimage',
            field=models.ImageField(blank=True, null=True, upload_to='download'),
        ),
    ]
