# Generated by Django 3.2.10 on 2023-08-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_downloaddb_rimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='favdb',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='favdb',
            name='ingredients',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='favdb',
            name='rimage',
            field=models.ImageField(blank=True, null=True, upload_to='favorites'),
        ),
    ]
