# Generated by Django 3.2.10 on 2023-08-17 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_auto_20230817_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favdb',
            name='rimage',
        ),
    ]
