# Generated by Django 3.2.10 on 2023-08-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_remove_favdb_rimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbackdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('feedback', models.EmailField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='downloaddb',
            name='rimage',
        ),
    ]
