# Generated by Django 3.2.10 on 2023-08-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_auto_20230818_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackdb',
            name='feedback',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
